### ISSUE TITLE
Method call validator should deref incoming documents

### ISSUE THREAD

**Issue by BelfordZ** [open-rpc/schema-utils-js#125]
https://github.com/open-rpc/schema-utils-js/blob/master/src/method-call-validator/method-call-validator.ts#L27

**Comment by BelfordZ** [comment]
I dont think it should  - it adds a perf overhead that is undesirable. Instead, we should document that the refs must be parsed first (https://github.com/open-rpc/schema-utils-js/issues/264), as well as provide a method for de-reffing a document (https://github.com/open-rpc/schema-utils-js/issues/263).

**Comment by zcstarr** [comment]
I'm hitting this right now 
![image](https://user-images.githubusercontent.com/173187/72110930-42a5f880-32ee-11ea-96d3-14b2997d313f.png)

**Comment by BelfordZ** [comment]
Closing in favor of https://github.com/open-rpc/schema-utils-js/issues/304
